repos:
  - repo: https://github.com/necaris/pre-commit-pyright
    rev: '1.1.53'
    hooks:
    - id: pyright
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.3'
    hooks:
    - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]
