site_name: table2sql

repo_url: https://github.com/piotrgredowski/table2sql

edit_uri: edit/main/docs/

theme:
  name: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - mkdocs-click
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.superfences

nav:
